export const step=[
    {
        id:0,
        title:'1-3月',
        title2:'主网第一阶段功能优化',
        time:'2018'
    },
    {
        id:1,
        title:'4-6月',
        title2:'主网第二阶段公测',
        time:'2019'
    },{
        id:2,
        title:'7月',
        title2:'主网并发交易开发',
        time:'2020'
    },{
        id:3,
        title:'9月',
        title2:'主网正式上线',
        time:'2021'
    },{
        id:4,
        title:'10-12月',
        title2:'优化虚拟机架构；搭建高效安全的智能合约；DAPP应用SDK开发；比特币跨链研发，共识层融合。',
        time:'2022'
    }
]